---
- name: Generate Kibana visualizations
  hosts: localhost
  roles:
    - visualize

  vars:
    index_pattern: omar-dev # Required
    kibana:

      # --- Ingest ---
      - visualization: Ingested Images
        file: visualizations/ingest/ingest-images.json

      - visualization: Ingested MissionIDs
        file: visualizations/ingest/ingest-missionids.json

      - visualization: Ingest Average Duration
        file: visualizations/ingest/ingest-average-duration.json

      - visualization: Ingested Images Count & Size
        file: visualizations/ingest/ingest-image-count-&-size.json

      - visualization: Ingest MissionID Count
        file: visualizations/ingest/ingest-missionid-count.json

      - visualization: Ingest MissionID Table
        file: visualizations/ingest/ingest-missionid-table.json

      - visualization: Ingest Image Summary
        file: visualizations/ingest/ingest-image-summary.json

      - search: Ingest Logs
        file: visualizations/ingest/ingest-logs.json

      - dashboard: Ingest Dashboard
        file: visualizations/ingest/ingest-dashboard.json
        panels:
          - visualization: Ingested Images
          - visualization: Ingested MissionIDs
          - visualization: Ingest Average Duration
          - visualization: Ingested Images Count & Size
          - visualization: Ingest MissionID Count
          - visualization: Ingest MissionID Table
          - visualization: Ingest Image Summary
          - search: Ingest Logs