---
- name: Generate Kibana visualizations
  hosts: localhost
  roles:
    - visualize

  vars:
    index_pattern: omar-dev # Required
    validate: no
    kibana:

      # --- Ingest ---
      - search: Ingest Logs
        file: visualizations/ingest/ingest-logs.json

      - visualization: Ingested Images
        file: visualizations/ingest/ingest-images.json

      - visualization: Ingested MissionIDs
        file: visualizations/ingest/ingest-missionids.json

      - visualization: Ingest Average Duration
        file: visualizations/ingest/ingest-average-duration.json

      - visualization: Ingested Images Count & Size
        file: visualizations/ingest/ingest-image-count-&-size.json
        search: Ingest Logs

      - visualization: Ingest MissionID Count
        file: visualizations/ingest/ingest-missionid-count.json
        search: Ingest Logs

      - visualization: Ingest MissionID Table
        file: visualizations/ingest/ingest-missionid-table.json
        search: Ingest Logs

      - visualization: Images on Ingest Queue
        file: visualizations/ingest/images-on-queue-chart.json

      - visualization: Latest Images Remaining on Ingest Queue
        file: visualizations/ingest/latest-images-remaining-on-queue.json

      - visualization: Ingest Image Summary
        file: visualizations/ingest/ingest-image-summary.json
        search: Ingest Logs

      - dashboard: Ingest Dashboard
        file: visualizations/ingest/ingest-dashboard.json
        panels:
          - visualization: Ingested Images
          - visualization: Ingested MissionIDs
          - visualization: Ingest Average Duration
          - visualization: Ingested Images Count & Size
          - visualization: Ingest MissionID Count
          - visualization: Ingest MissionID Table
          - visualization: Images on Ingest Queue
          - visualization: Latest Images Remaining on Ingest Queue
          - visualization: Ingest Image Summary
          - search: Ingest Logs

      # --- OGC Services ---
      - visualization: App Filter
        file: visualizations/ogc/app-filter-control.json
        description: A filter control to select an app by name

      - visualization: Response Time Average
        file: visualizations/ogc/average-response-time-chart.json
        description: Average response time split by app

      - visualization: HTTP Status Chart
        file: visualizations/ogc/http-status-chart.json
        description: Chart of HTTP status code split by app

      - visualization: HTTP Status Pie
        file: visualizations/ogc/http-status-pie.json
        description: Pie of HTTP status code split by app

      - visualization: OGC Dashboard Instructions
        file: visualizations/ogc/ogc-dashboard-instructions.json

      - visualization: Request Methods Pie
        file: visualizations/ogc/request-method-pie.json
        description: Pie of Request Methods split by app

      - visualization: Request Methods Cloud
        file: visualizations/ogc/request-method-word-cloud.json
        description: Word cloud of Request Methods

      - visualization: Response Size Chart
        file: visualizations/ogc/response-size-chart.json
        description: Chart of Response Size split by app

      - dashboard: OGC Services
        file: visualizations/ogc/ogc-dashboard.json
        description: High level view of all OGC apps
        panels:
          - visualization: Response Time Average
          - visualization: App Filter
          - visualization: OGC Dashboard Instructions
          - visualization: Response Size Chart
          - visualization: HTTP Status Pie
          - visualization: HTTP Status Chart
          - visualization: Request Methods Pie
          - visualization: Request Methods Cloud

      # --- Users ---
      - visualization: Concurrent Users Chart
        file: visualizations/users/concurrent-users.json

      - visualization: Machine-Human Interfaces Pie
        file: visualizations/users/machine-human-interfaces-pie.json

      - visualization: Unique Users Metric
        file: visualizations/users/unique-users-metric.json

      - visualization: Users Pie
        file: visualizations/users/users-pie.json
        description: A pie of user names by their number of hits

      - dashboard: Users
        file: visualizations/users/users-dashboard.json
        panels:
          - visualization: Users Pie
          - visualization: Unique Users Metric
          - visualization: Machine-Human Interfaces Pie
          - visualization: Concurrent Users Chart
